package constants

// Hello ...
var Hello = "Hello"

// KLogin ...
var KLogin = "KLogin"

// KGetMe ...
var KGetMe = "GET_ME"

// KGetStories ...
var KGetStories = "GET_STORIES"

// KGetUsers ...
var KGetUsers = "GET_USERS"

// KSessionSecret ...
var KSessionSecret = "SINNERMAN"

// KAuthSession ...
var KAuthSession = "AUTH_SESSION"

// KCurrentUser ...
var KCurrentUser = "CURRENT_USER"

// KNotAuthenticated ...
var KNotAuthenticated = "NOT_AUTHENTICATED"

// KNotAuthorized ...
var KNotAuthorized = "NOT_AUTHORIZED"

// KInvalidCredentials ...
var KInvalidCredentials = "INVALID_CREDENTIALS"

// KIsAuthenticated ...
var KIsAuthenticated = "IS_AUTHENTICATED"

// Request ...
var Request = "Request"

// Response ...
var Response = "Response"

// KMyContext ...
var KMyContext = "KMyContext"