package constants

// Hello ...
var Hello = "Hello"

// KLogin ...
var KLogin = "KLogin"

// KGetMe ...
var KGetMe = "GET_ME"

// KGetStories ...
var KGetStories = "GET_STORIES"

// KGetUsers ...
var KGetUsers = "GET_USERS"

// KSessionSecret ...
var KSessionSecret = "SINNERMAN"

// KAuthSession ...
var KAuthSession = "AUTH_SESSION"

// KCurrentUser ...
var KCurrentUser = "CURRENT_USER"

