// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GetMeResponse struct {
	Username string `json:"username"`
	ID       string `json:"id"`
}

type Hello struct {
	Reply string `json:"reply"`
}

type LoginParams struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

type RegisterParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}
